ALTER TABLE minha_coluna
ADD COLUMN grupo VARCHAR(255),
ADD COLUMN codigo VARCHAR(255),
ADD COLUMN data_referencia VARCHAR(255),
ADD COLUMN data_vencimento VARCHAR(255),
ADD COLUMN indexador VARCHAR(255),
ADD COLUMN taxa_emissao VARCHAR(255),
ADD COLUMN taxa_compra VARCHAR(255),
ADD COLUMN taxa_venda VARCHAR(255),
ADD COLUMN taxa_indicativa VARCHAR(255),
ADD COLUMN desvio_padrao VARCHAR(255),
ADD COLUMN val_min VARCHAR(255),
ADD COLUMN val_max VARCHAR(255),
ADD COLUMN pu VARCHAR(255),
ADD COLUMN pu_par VARCHAR(255),
ADD COLUMN duration	VARCHAR(255),
ADD COLUMN percent_renue VARCHAR(255),
ADD COLUMN data_fim VARCHAR(255),
ADD COLUMN hora_fim VARCHAR(255),
ADD COLUMN emissor VARCHAR(255),
ADD COLUMN referencia_ntnb VARCHAR(255),





